language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

env:
# Travis has slow VMs?
- blitzerThreads=1 blitzerActions=1 blitzerTimeout=1000

after_success:
  - mvn deploy --settings settings.xml
